When finding cameras on linux systems, look at camera ID before path or video*
pion/mediadevices pull request #476
Opened 2023-02-27 16:49 UTC by martha-johnston

#### Problem Description
Currently, it is not possible to detect a camera that has moved from one USB port to another on a linux system. This is the case because the `camera_linux.go` file implementation first looks at the paths in `/dev/v4l/by-path/*` and then in `/dev/video*` when looking for a camera object. The problem is that when USB cameras are moved around between USB ports on the linux system, the `by-path` and `video*` addresses may change. If there is a reference to the camera path, and then the camera is physically moved to a different USB port, the old path no longer exists and the camera cannot be opened. 

For example, observe the naming schema in `/dev/v4l/by-path/*` for a camera mapped to `/dev/video0`
```lrwxrwxrwx 1 root root 12 Feb 27 11:45 platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0-video-index0 -> ../../video0
lrwxrwxrwx 1 root root 12 Feb 27 11:45 platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0-video-index1 -> ../../video1 ```

The USB port is part of the name. For comparison, here is the same camera moved to a different USB port
``` lrwxrwxrwx 1 root root 12 Feb 27 11:45 platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1:1.0-video-index0 -> ../../video0
lrwxrwxrwx 1 root root 12 Feb 27 11:45 platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1:1.0-video-index1 -> ../../video1 ```

Note that the path has changed. When the server correctly detects that a camera previously disconnected from video0 has now been reconnected to video0 it will attempt to open the camera using the path saved during discovery. If the path is identical, i.e., it has been plugged back into the same USB port, then there’s no issue. However, if it moves USB paths, the old path no longer exists so it cannot be opened.  

#### Solution
In order to allow cameras to be switched between USB ports and still be accessible, the cameras must be identified by their ID, as that will never change regardless of where the camera is plugged in. This is a very simple change of looking in `dev/v4l/by-id/*` before `by-path` or `video*`.

Here is an example of a camera ID found in the newly created `dev/v4l/by-id` folder.
``` lrwxrwxrwx 1 root root 12 Feb 27 10:43 usb-EMEET_HD_Webcam_eMeet_C950_A220914000210705-video-index0 -> ../../video0
lrwxrwxrwx 1 root root 12 Feb 27 10:43 usb-EMEET_HD_Webcam_eMeet_C950_A220914000210705-video-index1 -> ../../video1 ```

And after the camera is moved to a different USB port, the path remains exactly the same.
``` lrwxrwxrwx 1 root root 12 Feb 27 11:44 usb-EMEET_HD_Webcam_eMeet_C950_A220914000210705-video-index0 -> ../../video0
lrwxrwxrwx 1 root root 12 Feb 27 11:44 usb-EMEET_HD_Webcam_eMeet_C950_A220914000210705-video-index1 -> ../../video1 ```

This change will allow for more flexibility for users who want to adjust their physical set up, as well as hopefully decrease troubleshooting and reinitializing when users do change their physical set ups and run in to issues.

2023-03-03 15:53 UTC, edaniels requested changes

2023-03-03 15:53 UTC, edaniels commented on pkg/driver/camera/camera_linux.go
> +	discover(discovered, "/dev/v4l/by-id/*")
Can you write a test for this and also describe how you've manually tested this?

2023-03-06 19:30 UTC, edaniels commented
@martha-johnston it looks like CI is failing. Can you take a look?

2023-03-06 19:54 UTC, martha-johnston commented
> @martha-johnston it looks like CI is failing. Can you take a look?

It's passing locally so not 100% sure but I think this change should fix it

2023-03-06 21:54 UTC, edaniels commented
That's still failing unfortunately. You may want to try using https://github.com/nektos/act to run that linux action to see if you can reproduce it.

2023-03-07 15:05 UTC, martha-johnston commented
> That's still failing unfortunately. You may want to try using https://github.com/nektos/act to run that linux action to see if you can reproduce it.

Should be solved now. Was able to reproduce and fix locally

2023-03-07 20:55 UTC, edaniels commented
HOORAY

2023-03-07 20:58 UTC, merged